<a href="https://colab.research.google.com/github/YG-0/Datascience_assisgnments/blob/main/Assignment_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("book.csv",encoding='latin-1')

In [ ]:
df.head()

   Unnamed: 0  ...  Book.Rating
0           1  ...            5
1           2  ...            3
2           3  ...            6
3           4  ...            8
4           5  ...            6

[5 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   10000 non-null  int64
 1   User.ID      10000 non-null  int64
 2   Book.Title   10000 non-null  object
 3   Book.Rating  10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

In [ ]:
df.rename({"User.ID":"User_id"},axis=1,inplace=True)

In [ ]:
df.rename({"Book.Title":"Book_title"},axis=1,inplace=True)

In [ ]:
df.rename({"Book.Rating":"Book_rating"},axis=1,inplace=True)

In [ ]:
df.head()

   Unnamed: 0  ...  Book_rating
0           1  ...            5
1           2  ...            3
2           3  ...            6
3           4  ...            8
4           5  ...            6

[5 rows x 4 columns]

In [ ]:
df['User_id'].nunique()

2182

In [ ]:
df['Book_title'].nunique()

9659

In [ ]:
user_df = df.pivot_table(index='User_id',columns='Book_title',values='Book_rating')

In [ ]:
user_df

Book_title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
User_id                           ...
8                            NaN  ...             NaN
9                            NaN  ...             NaN
10                           NaN  ...             NaN
12                           NaN  ...             NaN
14                           NaN  ...             NaN
...                          ...  ...             ...
278846                       NaN  ...             NaN
278849                       NaN  ...             NaN
278851                       NaN  ...             NaN
278852                       NaN  ...             NaN
278854                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [ ]:
user_df.index = df.User_id.unique()

In [ ]:
user_df

Book_title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                       NaN  ...             NaN
276729                       NaN  ...             NaN
276736                       NaN  ...             NaN
276737                       NaN  ...             NaN
276744                       NaN  ...             NaN
...                          ...  ...             ...
162107                       NaN  ...             NaN
162109                       NaN  ...             NaN
162113                       NaN  ...             NaN
162121                       NaN  ...             NaN
162129                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [ ]:
user_df.fillna(0, inplace=True)

In [ ]:
user_df

Book_title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                       0.0  ...             0.0
276729                       0.0  ...             0.0
276736                       0.0  ...             0.0
276737                       0.0  ...             0.0
276744                       0.0  ...             0.0
...                          ...  ...             ...
162107                       0.0  ...             0.0
162109                       0.0  ...             0.0
162113                       0.0  ...             0.0
162121                       0.0  ...             0.0
162129                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [ ]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [ ]:
user_sim = 1 - pairwise_distances( user_df.values,metric='cosine')

In [ ]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
user_sim_df = pd.DataFrame(user_sim)

In [ ]:
user_sim_df.index = df.User_id.unique()
user_sim_df.columns = df.User_id.unique()

In [ ]:
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [ ]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [ ]:
user_sim_df.idxmax(axis=1)[0:5]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
dtype: int64

In [ ]:
df[(df['User_id']==276736) | (df['User_id']==276726)]

   Unnamed: 0  ...  Book_rating
0           1  ...            5
3           4  ...            8

[2 rows x 4 columns]

In [ ]:
user_1=df[df['User_id']==276736]

In [ ]:
user_2=df[df['User_id']==276744]

In [ ]:
user_2.User_id

5    276744
Name: User_id, dtype: int64

In [ ]:
user_1.User_id

3    276736
Name: User_id, dtype: int64

In [ ]:
pd.merge(user_1,user_2,on='User_id',how='outer')

   Unnamed: 0_x  User_id  ...            Book_title_y  Book_rating_y
0           4.0   276736  ...                     NaN            NaN
1           NaN   276744  ...  The Kitchen God's Wife            7.0

[2 rows x 7 columns]